/**:
  ros__parameters:
    offboard:
      mass_of_system: 1.6
      lever_arm: 0.27
      gravitational_acceleration: 9.81
      moment_of_inertia: 0.375
      vehicle:
        servo_active: true
        motor_active: true
        servo_max_tilt_angle_degrees: 30.
        default_motor_pwm: 0.40 # active when position controllers are off
        motor_max_pwm: 0.8
        motor_thrust_curve: # newtons = (pwm * m + b) / 1000 * g;
          m: 2696.6
          b: -38.95
        delta_torque: # tau_delta_bar =  a * delta_M + b * M_bar + c
          a: 27.631
          b: 1.4667
          c: -0.702
      controller:
        attitude:
          active: [true, true, true]
          frequency_hertz: 50.
          gains:
            #   Roll, Pitch, Yaw
            k_p: [5.0, 5.0, 5.0]
            k_d: [2.0, 2.0, 2.0]
            k_i: [0.0, 0.0, 0.5]
        position: 
          active: true
          frequency_hertz: 50.
          gains:
            k_p:  [3.0, 3.0, 8.5]   # Proportional gain
            k_d:  [2.5, 2.5, 3.0]   # Derivative gain
            k_i:  [0.2, 0.2, 1.0]   # Integral gain
            k_ff: [1.0, 1.0, 1.0]   # Feedforward gain
            min_output: [-20., -20., -20.] # Minimum output of each PID
            max_output: [ 20.,  20.,  20.]
        generic:
          frequency_hertz: 100.
      mission:
        trajectory_setpoint:
          active: true
        takeoff_climb_height_meters: 0.6
        takeoff_climb_duration_seconds: 3.0
        landing_descent_duration_seconds: 4.0
